---

name: CI | Test

on:
  push:
    branches: [ '**' ]
#    paths:
#      - 'scripts/**'
#      - test
#      - configuration
#      - templates
  pull_request:
    branches: [ main ]
    paths:
      - 'scripts/**'
      - test
      - configuration
      - templates

jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 10 # this should not take longer thant that (for now)

    container:
      image: ghcr.io/grzegorznowak/cardano-node:1.33.0

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          repository: input-output-hk/cardano-db-sync
          ref: 12.0.2
          path: cardano-db-sync

      - name: WIP Battlegrounds | Test the cardano-db-sync
        run: |-
          apt install -y postgresql-client
          createdb -h postgres -p 5432 -U postgres privatenet
          git cherry-pick -n bff6e182cf41f6f7a9ff3d08bb1fc9984e2d0f66 \
          --git-dir=cardano-db-sync
          git cherry-pick -n 132f569bcd297ce73bca407a52acee513aa75389 \
          --git-dir=cardano-db-sync
          cd cardano-db-sync
          cabal build all
          ls -alhtr
        env:
          PGPASSWORD: postgres

      - name: Test the ephemeral devnet
        run: |-
          export PATH="/root/bin:${PATH}"
          export CARDANO_NODE_SOCKET_PATH=private-testnet/node-bft1/node.sock
          test/test_ephemeral_devnet.sh

      - name: Test the persistent devnet
        run: |-
          export PATH="/root/bin:${PATH}"
          export CARDANO_NODE_SOCKET_PATH=private-testnet/node-bft1/node.sock
          test/test_persistent_devnet.sh
